### ISSUE TITLE
Vertical sliders are broken in polyfill mode in range-capable browsers 

### ISSUE THREAD

**Issue by mourner** [freqdec/fd-slider#15]
Vertical sliders are broken in polyfill mode in browsers that natively support input type=range. You can see this by visiting the demo in Chrome: http://www.frequency-decoder.com/demo/fd-slider/

**Comment by freqdec** [comment]
Hi mourner,

Chrome doesn't follow the spec which is why you are seeing a broken range. Remember, the script has bowed out by this point as ranges are supported natively by the browser.

The spec stipulates that the orientation of the control should be determined from the ratio of the style-sheet-specified height and width properties. Basically, if you style the input height to be larger than the width, the browser should render a vertical range.

Chrome should have created a vertical range as I've styled the input height to be larger than the width but its current implementation is broken (which is a shame).

**Comment by mourner** [comment]
@freqdec I see, but if it's broken in Chrome, maybe it would be a good idea to detect if the user uses Chrome and switch to non-native vertical slider for such elements?

**Comment by freqdec** [comment]
This is something that, in my humble opinion, should be controlled by the developer. Adding this to the base script sounds like fools gold (someone will immediately ask to add an option to remove the functionality for example).

It would be possible to write a test that can be used within Modernizr.load that would load the files if on webkit and a vertical slider required e.g.

yepnope({
  test : Modernizr.inputtypes.range && myBespokeRangeTestForWebkit(),
  nope : ['fd-slider.js', 'fd-slider.css']
});

and within the markup...

// If slider script loaded then create range for vertical slider
if("fdSlider" in window && typeof (fdSlider.onDomReady) != "undefined") {
  fdSlider.createSlider({the options});
};

**Comment by mourner** [comment]
Sounds reasonable, OK then. :)
