### ISSUE TITLE
position:fixed sliders not reacting correctly to mouse events

### ISSUE THREAD

**Issue by freqdec** [freqdec/fd-slider#16]
If a slider is position:fixed, clicking on the range bar will not animate the drag-handle to the click-point. The code needs updated to correctly calculate the click position when fixed positioning is used.

**Comment by ghost** [comment]
Any idea on how to fix this? I'm using the slider inside a Twitter Bootstrap modal and although dragging the handle works, clicking on the range bar doesn't.

**Comment by padraicm** [comment]
https://github.com/padraicm/fd-slider/commit/35efc37d53bc5d0a1f00a249e021ff029496f072

**Comment by ghost** [comment]
Can you please merge @padraicm's code in in? At the moment you have a broken implementation, you need to remove this line - https://github.com/freqdec/fd-slider/blob/master/js/fd-slider.js#L785
Otherwise you are stepping up 2 levels at a time (once inside the loop, then once inside the condition).
If you want to keep the `obj = obj.offsetParent` in the loop, just check for `while(obj)` instead of doing the assignment.  e.g

```
                do {
                    curleft += obj.offsetLeft;
                    curtop  += obj.offsetTop;
                    obj      = obj.offsetParent;
                } while(obj);
```

**Comment by ghost** [comment]
I've created a pull request - https://github.com/freqdec/fd-slider/pull/39 which removes the unnecessary assignment that should fix this bug.
