### ISSUE TITLE
Slider breaks if parent block is hidden during creation

### ISSUE THREAD

**Issue by Noino** [freqdec/fd-slider#20]
The parent block is hidden during creation, and the slider when shown, gets stuck at the 0 position, but value is set to about half to max of whats possible when you try to move it. Resizing browser window seems to repair the slider, nob moves to its correct position and you are once again able to change the value.

reproduced: http://test.wendell.fi/fdslidertest/test.html
- Relevant for (atleast): FF 11, Chrome 18, Opera 11.62

IE8 seems to handle this without problems tho

**Comment by freqdec** [comment]
The slider needs to know it's width/height in order to calculate the pixel increment. Hidden sliders return a zero value which makes things break (but apparently not in IE8 - how strange).

You can always call the updateSlider method whenever the parent has been shown. This will recalculate the increment and make the slider work as expected.

**Comment by Noino** [comment]
updateSlider doesnt seem to fix it, and while redrawAll seems to fix this one it does not look foolproof either.

Don't like the idea of redrawing all sliders each time one is shown but i guess that's where we're at atm

**Comment by freqdec** [comment]
Just fixed the problem. I forgot to call the sliders redraw method from within the fdSlider.updateSlider method. Silly me.

Thanks for taking the time to post the issue.
